name: tvb
channels:
  - conda-forge
dependencies:
  #- python=3.13
  - python=3.11
  - numpy=1.26
  - scipy=1.14
  - matplotlib=3.9
  - jupyterlab=4
  - ipykernel=6
  - python-dotenv
  - rich
  - pip
  #- pip:
  #    - tvb-library==2.10.0


##############################################
## Instalación
# mamba env create -f conda/environment.yml


###############################################
## Crear un entrono Jupyter
# mamba run -n tvb python -m ipykernel install --user \
#     --name tvb \
#     --display-name "Python (tvb)"

###############################################
## Instalación manual de paquetes adicionales:
#
# mamba activate tvb
# pip install tvb-library==2.10.0
#
## Opción 2
#
# micromamba run -n tvb python -m pip install tvb-library==2.10.0
